#pragma once

#define BOUND 80.0f
#define BOUNDINT (int)BOUND
#define RADIUS 1
#define COLLISIONDIST (float)(2*RADIUS+1)
#define STARTINGDIST ((float)2*RADIUS+1.3f)
#define SPRINGFORCE 0.5f
#define GRAVITY -0.0004f
#define DAMPING 0.012f
#define BOUNDARYFORCE 0.5f
#define SHEARFORCE 0.03f

#define CELLSIZE 8
#define LOGGRIDSIZE 10
#define CELLCOUNTX 4096
#define CELLCOUNTY 4096
#define CELLCOUNT (CELLCOUNTX * CELLCOUNTY )

#define DOWNSAMPLING 16
#define DOWNSAMPLINGSQR 256
#define LOGDOWNSAMPLINGSQR 8
#define IMAGEW 1920
#define IMAGEH 1080
#define IMAGEWFULL (IMAGEW*DOWNSAMPLING)
#define IMAGEHFULL (IMAGEH*DOWNSAMPLING)

#define FRAMEDIFF 2
#define FADEFRAMES 50
#define FRAMECOUNT 100000

#define LOGOW 240
#define LOGOH 234
#define DPPX 16
#define PARTICLECOUNTX (DPPX*LOGOW)
#define PARTICLECOUNTY (DPPX*LOGOH)
#define PARTICLECOUNT (PARTICLECOUNTX*PARTICLECOUNTY)

#define SPEEDFACTOR 1000000

#define THREADCOUNT 16